version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: diary-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: diary_db
      MYSQL_USER: diary_user
      MYSQL_PASSWORD: diary_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - diary-network

  # 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: diary-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: diary_user
      DB_PASSWORD: diary_password
      DB_DATABASE: diary_db
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - diary-network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: diary-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - diary-network

volumes:
  mysql_data:

networks:
  diary-network:
    driver: bridge
